export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_ASSIGNMENTS_START = 'FETCH_ASSIGNMENTS_START';
export const FETCH_ASSIGNMENTS_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_ASSIGNMENTS_FAILED = 'FETCH_ASSIGNMENTS_FAILED';

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILED = 'FETCH_STUDENTS_FAILED';

export const FETCH_CLASSES_START = 'FETCH_ASSIGNMENTS_START';
export const FETCH_CLASSES_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_CLASSES_FAILED = 'FETCH_ASSIGNMENTS_FAILED';

export const ADD_ASSIGNMENTS_START = "ADD_ASSIGNMENTS_START";
export const ADD_ASSIGNMENTS_SUCCESS = "ADD_ASSIGNMENTS_SUCCESS";
export const ADD_ASSIGNMENTS_FAILED = "ADD_ASSIGNMENTS_FAILED";

export const SUBMIT_ANSWERS_START = "SUBMIT_ANSWERS_START";
export const SUBMIT_ANSWERS_SUCCESS = "SUBMIT_ANSWERS_SUCCESS";
export const SUBMIT_ANSWERS_FAILED  = "SUBMIT_ANSWERS_FAILED";
